language: csharp

sudo: required
dist: trusty

# have to add dotnet to each mono build config because Travis doesn't have an 'include both runtimes' option
matrix:
  include:
    - os: linux
    - os: osx
  # The whole build matrix fails when any individual builds fail (except those which have been allowed with allow_failures).
  fast_finish: true

script:
  - ./build.sh -t CleanInternetCaches && ./build.sh -t All

branches:
  except:
  - gh-pages
  - release
