image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd -t CleanInternetCaches
  - cmd: build.cmd -t AppVeyorBuildVersion
  - cmd: build.cmd -t All
  - cmd: build.cmd -t NuGet

matrix:
  fast_finish: true

test: off

artifacts:
  - path: bin\*.nupkg

branches:
  except:
    - gh-pages
    - release
